language: node_js
node_js:
  - "10.15.3"
cache: npm

install:
  - npm install

script:
  - npm run build

deploy:
  provider: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
